### ISSUE TITLE
Alter Table Exercise

### ISSUE THREAD

**Issue by gitsegun** [gitsegun/mysql_track#1]
NEW URL: https://github.com/gitsegun/mysql_track/tree/master/alter_table

Create a table named "testing_table" with following fields:
name (string), contact_name (string), roll_no (string)
Now:
1. Delete column name
2. Rename contact_name to username.
3. Add two fields first_name, last_name.
4. Change the type of roll_no to integer

**Comment by segunadeleye** [comment]
Looks good!
