### ISSUE TITLE
Backup and restore Exercise

### ISSUE THREAD

**Issue by gitsegun** [gitsegun/mysql_track#3]
URL:  https://github.com/gitsegun/mysql_track/tree/master/exercise_four

 Backup and Restore
Take backup of the db you created for practice/exercise and send it to me. Now create a new
database named "restored" and restore that backup into this DB.

**Comment by segunadeleye** [comment]
`mysqldump` is not the correct command here. It is used for backing up and not for restoring database.

**Comment by gitsegun** [comment]
@segunadeleye  The right command for restoring a backup database has been added

**Comment by segunadeleye** [comment]
Looks good.
