### ISSUE TITLE
Email Campaign

### ISSUE THREAD

**Issue by gitsegun** [gitsegun/mysql_track#4]
URL: https://github.com/gitsegun/mysql_track/tree/master/exercise_five

 Email Campaign Data Exercise
We ran a campaign on a website, asking people to submit their email address, their city and
phone number. The data was collected in a csv format - The file is here...
http://dl.dropbox.com/u/628209/exercises/mysql/email_subscribers.txt
First import this csv data into a mysql database. From the database, we need to find the
following information by writing a single SQL statement for each;

● What all cities did people respond from
● How many people responded from each city
● Which city were the maximum respondents from?
● What all email domains did people respond from ?
● Which is the most popular email domain among the respondents ?

**Comment by gitsegun** [comment]
@segunadeleye Correction request "adding questions by comments" and indenting the code.

**Comment by gitsegun** [comment]
@segunadeleye proper indentation according to mysql study guide

**Comment by segunadeleye** [comment]
- https://github.com/gitsegun/mysql_track/blob/master/exercise_five/mail_campaign.sql#L47-L51
If there are more than one city with maximum respondents, this query will only return one.

- https://github.com/gitsegun/mysql_track/blob/master/exercise_five/mail_campaign.sql#L71-L76
Just like I stated above, this query will return just one domain even if there are more then one domain with with the highest number of respondents.

**Comment by gitsegun** [comment]
Correction made to max count @segunadeleye

**Comment by segunadeleye** [comment]
The queries still will not give us the required results.

**Comment by gitsegun** [comment]
Correction made. Kindly check

**Comment by gitsegun** [comment]
I did correction to my indentation

**Comment by segunadeleye** [comment]
Looks good!
