### ISSUE TITLE
Sanwishes Exercise One

### ISSUE THREAD

**Issue by gitsegun** [gitsegun/mysql_track#5]
URL: https://github.com/gitsegun/mysql_track/tree/master/exercise_one

Write SQL statements to retrieve the following information:
(i) places where Jones can eat (using a nested subquery).
(ii) places where Jones can eat (without using a nested subquery).
(ii) for each location the number of people who can eat there.

**Comment by segunadeleye** [comment]
- https://github.com/gitsegun/mysql_track/blob/master/exercise_one/sandwich.sql#L54
https://github.com/gitsegun/mysql_track/blob/master/exercise_one/sandwich.sql#L58
Use `JOIN`

- https://github.com/gitsegun/mysql_track/blob/master/exercise_one/sandwich.sql#L55
https://github.com/gitsegun/mysql_track/blob/master/exercise_one/sandwich.sql#L60
`(tastes.filling = sandwiches.filling)` not `(tastes.filling=sandwiches.filling)`

**Comment by gitsegun** [comment]
Correction and indentation changes done.
