### ISSUE TITLE
Library.sql exercise-one

### ISSUE THREAD

**Issue by gitsegun** [gitsegun/mysql_track#8]
URL: https://github.com/gitsegun/mysql_track/tree/master/exercise_one

Write SQL statements to retrieve the following information:
(i) the  names of all library books published by Macmillan.
(ii) branches that hold any books by Ann Brown (using a nested subquery).
(iii) branches that hold any books by Ann Brown (without using a nested subquery).
(iv) the total number of books held at each branch.

**Comment by gitsegun** [comment]
Indentation guideline.

**Comment by segunadeleye** [comment]
All good. Just a correction here https://github.com/gitsegun/mysql_track/blob/master/exercise_one/library.sql#L84-L85
Put space on both sides of `=`
